#!/usr/bin/python

import os
from time import localtime,strftime

E2_BINPATH = '/usr/local/bin/enigma2'
E2_BINPATH2 = '/usr/bin/enigma2'

def main():
    try:
        e2t = localtime(os.path.getmtime(E2_BINPATH))
        print strftime('%Y%m%d',e2t)
    except OSError:
        e2t = localtime(os.path.getmtime(E2_BINPATH2))
        print strftime('%Y%m%d',e2t)

if __name__=='__main__':
    main()
