#!/bin/sh

GSTREAMER='/usr/lib/gstreamer-0.10'
ARCHIVCZSK='/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK'
TMP='/tmp/archivczsk'

check_py ()
{
if [ -e $1o -o -e $1 ]
then
	echo '0'
else
	echo '1'
fi
}

get_oe ()
{
if [ -f /lib/libcrypto.so.1.0.0 ]
then
        oe="OE4"
else
        oe="OE16-3"
fi
echo  $oe
}


get_platform ()
{
local platform=$(uname -m)

if [ "$platform" == "sh4" ]
then
	platform="sh4"
else
	if [ `ls -al /usr/lib/python2.7 | grep urllib.pyo | wc -l` -gt 0 ];
	then
		platform="mips32el"
	else
		platform="mipsel"
	fi
fi
echo $platform
}

get_arch (){
local arch=$(get_platform)
if [ "$arch" == "misp32el" ]
then
	arch="mipsel"
fi
echo $arch
}

sh4_install ()
{
echo 'Installing librtmp'
if [ -f /usr/lib/librtmp.so.0 ] || [ -f /usr/lib/librtmp.so.1 ];
then
	echo "Found librtmp, not needed to install"
else
	cp $TMP/sh4/rtmpdump/librtmp.so.0 /usr/lib/librtmp.so.0
	ln -s /usr/lib/librtmp.so.0 /usr/lib/librtmp.so
	chmod 755 /usr/lib/librtmp.so.0
	chmod 755 /usr/lib/librtmp.so
fi

rm -R $ARCHIVCZSK/script

if [ -d $GSTREAMER ];
then
	echo "Found gstreamer"
	if [ -e $GSTREAMER/libgstrtmp.so ]
	then
		echo "Found libgstrtmp.so"
	else
		echo "Installing libgstrtmp.so"
		cp $TMP/sh4/gst_rtmp_plugin/libgstrtmp.so $GSTREAMER/libgstrtmp.so
		chmod 755 $GSTREAMER/libgstrtmp.so
	fi
fi
}


install_py ()
{
if [ "$(check_py $2)" == '1' ]
   then
	echo "Installing $1 ..."
   	cp $1 $2
fi
}

PLATFORM=$(get_platform)
OE=$(get_oe)

echo "Installation for $PLATFORM platform"

echo 'Installing pngquant...'
if [ "$PLATFORM" == "sh4"  ]; then
	cp $TMP/$PLATFORM/pngquant/pngquant /usr/bin/
else
	if [ "OE" == "OE4" ]; then
		echo 'skipping...'
	else
		cp $TMP/mipsel/pngquant/OE16/pngquant /usr/bin
	fi
fi
chmod 755 /usr/bin/pngquant

if [ "$PLATFORM" == "sh4" ]
then sh4_install
fi

chmod 755 $ARCHIVCZSK/script/*.sh 2>/dev/null

echo 'Installing neccessary Python libraries'
if [ -d /usr/lib/python2.6 ]
then
	echo "Found Python 2.6"
	cd  $TMP/python2.6
	install_py ./utf_8.py /usr/lib/python2.6/encodings/utf_8.py
	install_py ./cp1251.py /usr/lib/python2.6/encodings/cp1251.py
	install_py ./cp1252.py /usr/lib/python2.6/encodings/cp1252.py
	install_py ./cp1253.py /usr/lib/python2.6/encodings/cp1253.py
	install_py ./cp1254.py /usr/lib/python2.6/encodings/cp1254.py
	install_py ./cp1256.py /usr/lib/python2.6/encodings/cp1256.py
	install_py ./iso8859_6.py /usr/lib/python2.6/encodings/iso8859_6.py
	install_py ./iso8859_7.py /usr/lib/python2.6/encodings/iso8859_7.py
	install_py ./iso8859_9.py /usr/lib/python2.6/encodings/iso8859_9.py
	install_py ./iso8859_15.py /usr/lib/python2.6/encodings/iso8859_15.py
	install_py ./hex_codec.py /usr/lib/python2.6/encodings/hex_codec.py
	install_py ./latin_1.py /usr/lib/python2.6/encodings/latin_1.py
	install_py ./utf_16.py /usr/lib/python2.6/encodings/utf_16.py
	install_py ./string_escape.py /usr/lib/python2.6/encodings/string_escape.py
	install_py ./idna.py /usr/lib/python2.6/encodings/idna.py
	install_py ./iso8859_2.py /usr/lib/python2.6/encodings/iso8859_2.py
	install_py ./cp1250.py /usr/lib/python2.6/encodings/cp1250.py
	install_py ./decimal.py /usr/lib/python2.6/decimal.py
	install_py ./formatter.py /usr/lib/python2.6/formatter.py
	install_py ./htmlentitydefs.py /usr/lib/python2.6/htmlentitydefs.py
	install_py ./markupbase.py /usr/lib/python2.6/markupbase.py
	install_py ./htmlentitydefs.py /usr/lib/python2.6/htmlentitydefs.py
	install_py ./htmllib.py /usr/lib/python2.6/htmllib.py
	install_py ./markupbase.py /usr/lib/python2.6/markupbase.py
	install_py ./sgmllib.py /usr/lib/python2.6/sgmllib.py
	install_py ./stringprep.py /usr/lib/python2.6/stringprep.py
	install_py ./subprocess.py /usr/lib/python2.6/subprocess.py
	install_py ./numbers.py /usr/lib/python2.6/numbers.py
	install_py ./_LWPCookieJar.py /usr/lib/python2.6/_LWPCookieJar.py
	install_py ./_MozillaCookieJar.py /usr/lib/python2.6/_MozillaCookieJar.py
	install_py ./cookielib.py /usr/lib/python2.6/cookielib.py
	install_py ./shutil.py /usr/lib/python2.6/shutil.py
	install_py ./fnmatch.py /usr/lib/python2.6/fnmatch.py
	install_py ./threading.py /usr/lib/python2.6/threading.py
	install_py ./zipfile.py /usr/lib/python2.6/zipfile.py
	install_py ./stat.py /usr/lib/python2.6/stat.py
	install_py ./httplib.py /usr/lib/python2.6/httplib.py
fi

if [ -d /usr/lib/python2.7 ]
then
	echo "Found Python 2.7"
	cd $TMP/python2.7
	install_py ./utf_8.py /usr/lib/python2.7/encodings/utf_8.py
	install_py ./cp1251.py /usr/lib/python2.7/encodings/cp1251.py
	install_py ./cp1252.py /usr/lib/python2.7/encodings/cp1252.py
	install_py ./cp1253.py /usr/lib/python2.7/encodings/cp1253.py
	install_py ./cp1254.py /usr/lib/python2.7/encodings/cp1254.py
	install_py ./cp1256.py /usr/lib/python2.7/encodings/cp1256.py
	install_py ./iso8859_6.py /usr/lib/python2.7/encodings/iso8859_6.py
	install_py ./iso8859_7.py /usr/lib/python2.7/encodings/iso8859_7.py
	install_py ./iso8859_9.py /usr/lib/python2.7/encodings/iso8859_9.py
	install_py ./iso8859_15.py /usr/lib/python2.7/encodings/iso8859_15.py
	install_py ./hex_codec.py /usr/lib/python2.7/encodings/hex_codec.py
	install_py ./latin_1.py /usr/lib/python2.7/encodings/latin_1.py
	install_py ./utf_16.py /usr/lib/python2.7/encodings/utf_16.py
	install_py ./iso8859_2.py /usr/lib/python2.7/encodings/iso8859_2.py
	install_py ./cp1250.py /usr/lib/python2.7/encodings/cp1250.py
	install_py ./string_escape.py /usr/lib/python2.7/encodings/string_escape.py
	install_py ./idna.py /usr/lib/python2.7/encodings/idna.py
	install_py ./decimal.py /usr/lib/python2.7/decimal.py
	install_py ./formatter.py /usr/lib/python2.7/formatter.py
	install_py ./htmlentitydefs.py /usr/lib/python2.7/htmlentitydefs.py
	install_py ./htmllib.py /usr/lib/python2.7/htmllib.py
	install_py ./HTMLParser.py /usr/lib/python2.7/HTMLParser.py
	install_py ./markupbase.py /usr/lib/python2.7/markupbase.py
	install_py ./stringprep.py /usr/lib/python2.7/stringprep.py
	install_py ./sgmllib.py /usr/lib/python2.7/sgmllib.py
	install_py ./subprocess.py /usr/lib/python2.7/subprocess.py
	install_py ./numbers.py /usr/lib/python2.7/numbers.py
	install_py ./fnmatch.py /usr/lib/python2.7/fnmatch.py
	install_py ./_LWPCookieJar.py /usr/lib/python2.7/_LWPCookieJar.py
	install_py ./_MozillaCookieJar.py /usr/lib/python2.7/_MozillaCookieJar.py
	install_py ./cookielib.py /usr/lib/python2.7/cookielib.py
	install_py ./shutil.py /usr/lib/python2.7/shutil.py
	install_py ./threading.py /usr/lib/python2.7/threading.py
	install_py ./zipfile.py /usr/lib/python2.7/zipfile.py
	install_py ./stat.py /usr/lib/python2.7/stat.py
	install_py ./httplib.py /usr/lib/python2.7/httplib.py
fi

if [ -f $TMP/categories.xml ];
then
	echo "Found categories.xml, restoring..."
	cp $TMP/categories.xml $ARCHIVCZSK
fi
if [ -d $TMP/data/ ];
then
	echo "Found DATA, restoring..."
	if [ -d $ARCHIVCZSK/resources/data ]; then
		rm -rf $ARCHIVCZSK/resources/data
	fi
	cp -R $TMP/data $ARCHIVCZSK/resources
fi

echo "Removing temp folder..."
rm -rf $TMP

echo "Installation of archivCZSK was successfull"

exit 0
